version: "3.3"
services:
  web:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./public:/usr/share/nginx/html
  node:
    image: node
    working_dir: /work
    volumes:
      - ./:/work